name: verify-pull-request

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  NODE_ENV: test

jobs:
  lint:
    name: Run Linter
    runs-on: ubuntu-latest
    steps:
      - name: Fetch from Git
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install Node.js dependencies
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
      - name: Run tslint
        run: yarn tslint

  build:
    name: Run build
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Fetch from Git
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install Node.js dependencies
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
      - name: Run build
        run: yarn build-ts
  tests:
    name: Run tests
    needs: build
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      MYSQL_PORT: 3308
      MYSQL_HOST: localhost
      MYSQL_USERNAME: root # for running tests using testcontainer module
      MYSQL_PASSWORD: root # idem username
      MYSQL_DATABASE: test_container
      MYSQL_VERSION: 5.7.32
      MYSQL_TIMEZONE: +00:00
    steps:
      - name: Fetch from Git
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install Node.js dependencies
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
      - name: Run tests
        run: yarn test
